import Head from "next/head";
import { useState } from "react";
import Footer from "../../components/footer";
import Header from "../../components/header";
import TopOfPage from "../../components/topOfPage";
import Guidecks from "./Guidecks";
import Hero from "../_hero";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className="">
      <TopOfPage isOpen={isOpen} />
      <Head>
        <title>Josh Gretton portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className=" ">
        <Header isOpen={isOpen} setIsOpen={setIsOpen} />
        <div
          className={`${
            isOpen ? " opacity-0 duration-300" : " opacity-100 duration-300"
          } xl:container fixed mx-auto px-4 sm:px-16 inset-x-0 top-0 pt-12 h-v60 flex items-center -z-10 bg-white transition-all transform`}
        >
          <h2 className="tracking-widest md:text-5xl font-light text-2xl sm:text-4xl">
            <span className="text-blue-300">Guidecks</span>
          </h2>
        </div>
      </header>

      <main
        className={
          isOpen
            ? " xl:container xl:mx-auto sm:mt-v40 mt-96   bg-white sm:px-10 transition-opacity duration-700 opacity-0"
            : "xl:container xl:mx-auto sm:mt-v40 mt-96   bg-white sm:px-10  transition-opacity  duration-300 opacity-100"
        }
      >
        <Guidecks />
      </main>

      <footer>
        <Footer />
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>

      {/* <footer className="">
      </footer> */}
    </div>
  );
}
