import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Header from "../components/header";
import Hero from "./hero";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className="">
      <Head>
        <title>Josh Gretton portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className=" ">
        <Header isOpen={isOpen} setIsOpen={setIsOpen} />
        {/* <Hero isOpen={isOpen} /> */}
      </header>

      {/* <footer className="">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
